name: Diamond Bot
on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install System Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg
          
      - name: Install Python Libraries
        run: |
          pip install --upgrade pip
          pip install yt-dlp google-api-python-client googlesearch-python google-auth-oauthlib

      - name: Run Script
        run: python main.py
        
